name: ExtDN Static Tests
on:
  pull_request:
    branches:
      - main
jobs:
  static:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-coding-standard@master
        with:
          phpcs_standard: phpcs.xml
      - uses: extdn/github-actions-m2/magento-mess-detector@master
